return {
	Placeholder1 = {
		DisplayName = "Placeholder One",
		Model = "Placeholder1",
		HP = 100,
		Damage = 50,
		Range = 16,
		AttackCooldown = .4,
	},

	Placeholder2 = {
		DisplayName = "Placeholder Two",
		Model = "Placeholder2",
		HP = 120,
		Damage = 40,
		Range = 100,
		AttackCooldown = 1.5,
	},

	Placeholder3 = {
		DisplayName = "Placeholder Three",
		Model = "Placeholder3",
		HP = 90,
		Damage = 15,
		Range = 12,
		AttackCooldown = 0.6,
	},
}
